### ISSUE TITLE
Story component isolation (styles, js)

### ISSUE THREAD

**Issue by mergebandit** [hydrateio/docz-plugin-storybook#2]
Currently, storybook wraps each story in an iFrame to ensure components are being rendered in true isolation, and don't suffer from style / script bleed.

We should provide the same level of protection.

![It is known](https://media.giphy.com/media/10hexADl3Kl6SY/giphy.gif)

**Comment by transitive-bullshit** [comment]
👍 to the gif 👍 

One question here is how do we handle iframe sizing? Storybook punts on this and sets iframes to 100%x100% which is pretty weak cause you end up having buttons that take up the whole viewport.

This isn't a concern when we have no iframe wrappers, but it's something wee need to be explicit about once we add in iframes.

Maybe the default behavior is to not add iframes and they're opt-in by default?

**Comment by natergj** [comment]
If the iframe shows a button that expands to the height/width of the container then this might actually be ideal as it would show the developer that they may want to add some sizing props to their button (or whatever component it is).  In past work I have seen many components with missing styles because they rely on global styles or styles set higher in the DOM tree. There are many opinions about styles and stylesheets these days.  If a development team sways towards relying on stylesheets where element properties are inherited, then the iframe method may break something if not implemented correctly. If the development teams sways towards styling elements in isolation, the iframe method would help them to ensure that components are styled in this way. We also want to make certain that the styles set to theme the storybook itself (something a user can augment) does not leek into the components. 

I think using the iframes by default with an option to disable them may be the best option.

**Comment by transitive-bullshit** [comment]
Closed by #6 thanks to @kevindavi5 👍
